### ISSUE TITLE
Error while compiling with cmake: missing source file "src/surgescript/runtime/sslib/plugin.c" required by CMakeLists

### ISSUE THREAD

**Issue by cafeina-software** [alemart/surgescript#1]
> user@user:~/surgescript/build$ cmake ..
> -- The C compiler identification is GNU 7.3.0
> -- The CXX compiler identification is GNU 7.3.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> CMake Error at CMakeLists.txt:88 (add_library):
>   Cannot find source file:
> 
>     src/surgescript/runtime/sslib/plugin.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> 
> 
> CMake Error: Cannot determine link language for target "surgescript".
> CMake Error: CMake can not determine linker language for target: surgescript
> -- Generating done
> -- Build files have been written to: /home/user/surgescript/build
> 

Also `make` command failed due to the above.

If in CMakeLists.txt is commented line 35 (missing plugin.c)
`# src/surgescript/runtime/sslib/plugin.c`
then cmake gives an error about lookup3.c missing. After commented line 47 (missing lookup3.c), 
`# src/surgescript/util/lookup3.c`
`cmake` exits successfully, but `make` throws an error about undefined references.

This issue seems to be a regression from one of the commits which introduced "Plugins (WIP)".

**Comment by alemart** [comment]
Hello,

Please get the latest commit and try again.

Thanks for reporting.

**Comment by cafeina-software** [comment]
Now sources compile. It's solved.
