### ISSUE TITLE
[minor] AUR -DCMAKE_INSTALL_PREFIX=/usr

### ISSUE THREAD

**Issue by ghost** [alemart/surgescript#10]
The convention is that third party packages install their stuff in the normal places, local is for when you bypass the package manager.

**Comment by alemart** [comment]
/usr/local is the default value of `CMAKE_INSTALL_PREFIX`. It is meant to be [used by system administrators when installing software locally](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) and is typically used to store locally built programs. Package maintainers and individual users may change that setting as they deem appropriate.

**Comment by ghost** [comment]
That wording comes from 1994, before package managers even  existed. It used to be all manual.

Today, local has degenerated to be used for manual installs that bypass the package manager.... Because the package manager is .... managing the packages. If packages collide, the package manager will not install them.

A major example is pip that installs in local, if you build a AUR python package that installs in local, it will collide with the pip version.

The package manager shouldn't install in local, because that folder is managed manually by the user. The package manager can never know what's there already.

**Comment by alemart** [comment]
That link points to the Filesystem Hierarchy Standard version 3.0, released in 2015, when package managers were already widespread. SurgeScript can be manually built from this repository and installing it into /usr/local is appropriate in this case.

I don't maintain any distro-specific packages. Package maintainers are free to change that setting as they see fit.

**Comment by ghost** [comment]
Oups, for some reason i thought you were maintaining the AUR package.
