### ISSUE TITLE
Add SONAMEs to libsurgescript

### ISSUE THREAD

**Issue by suve** [alemart/surgescript#4]
SurgeScript can now be compiled as a shared library, `libsurgescript`. However, the produced `.so` contains only one SONAME, which means that an application using SurgeScript is bound to a specific version of SurgeScript and must be rebuilt when SurgeScript is updated (e.g. if I build an application using SS 0.5.4.3, and update SS to 0.5.4.4, then the application won't run anymore since it specifically requires 0.5.4.3).

Adding SONAMEs would allow applications to specify that they need e.g. SurgeScript 0.5, and then be able to use 0.5.0, 0.5.1, 0.5.1.1, etc. Of course, this necessitates keeping some degree of backwards compatibility within the library (looking at the release log, there already is some).

**Comment by alemart** [comment]
Thank you for your suggestion. I'll take it into account on the next version.
