### ISSUE TITLE
Compiling Instructions?

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [alemart/surgescript#9]
I recently found this project and i'm loving but i'm currently having issues to compile this since under Visual studio 2022 it fails to find `threads.h`

**Comment by alemart** [comment]
Thank you for your comment. :+1:

Disable `WANT_EXECUTABLE_MULTITHREAD` in CMake and make sure you use clang with Visual Studio.

**Comment by alemart** [comment]
Closed due to inactivity. If you have further questions, feel free to get in touch again.
